/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define NVIC_ISPR0 0XE000E200U
#define NVIC_ISPR1 (NVIC_ISPR0+4)
#define NVIC_ISER0 0xE000E100U
#define NVIC_IPR0 0xE000E400U
#define TIM2_IRQ 28
#define I2C1_IRQ 31

	volatile uint32_t *const pNVIC_ISPR0=(uint32_t *) NVIC_ISPR0; //pending set register pointer
	volatile uint32_t *const pNVIC_ISER0=(uint32_t *) NVIC_ISER0; //set enable register pointer

void setPriority(uint8_t IRQ_NO,uint8_t priority)
{
	uint8_t registerNo=IRQ_NO/4;
	uint8_t lshift=(IRQ_NO%4)*8;
	volatile uint32_t *const pNVIC_IPRx=(uint32_t *)(NVIC_IPR0+registerNo*4); //desired priority register
	*pNVIC_IPRx&=~(0xff<<lshift);
	*pNVIC_IPRx|=(priority<<lshift);

}

int main(void)
{

//	volatile uint32_t *const pNVIC_IPR0=(uint32_t *) NVIC_IPR0; //set priority register pointer

	//priority set for TIM2
	setPriority(28,0x80);

	//priority set for I2C1
	setPriority(31, 0x70);

	//interrupt enable for TIM2
	*pNVIC_ISER0|=(1<<TIM2_IRQ);

	//interrupt enable for I2C1
	*pNVIC_ISER0|=(1<<I2C1_IRQ);

	//interrupt pending enable for TIM2
	*pNVIC_ISPR0|=(1<<TIM2_IRQ);

	//interrupt pending enable for I2C
	*pNVIC_ISPR0|=(1<<I2C1_IRQ);




    /* Loop forever */
	for(;;);
}

void TIM2_IRQHandler()
{
	printf("In the Timer interrupt\n");
	*pNVIC_ISPR0|=(1<<I2C1_IRQ);
	while(1);

}

void I2C1_EV_IRQHandler()
{
	printf("In the I2C event interrupt\n");
}
